spring:
  application:
    name: serviceProvider

server:
  port: 2222

eureka:
  instance:
    hostname: serviceProvider
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/