spring:
  application:
    name: client2

server:
  port: 2222
  context-path: /localhost

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/